title: 'Board of Architects'
title-abbreviated: BOA
description: 'The Board of Architects is the statutory authority established to administer the Architects Act in Singapore.'
url: 'https://www.boa.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
collections:
    register:
        output: true
    who-we-are:
        output: true
    be-an-architect:
        output: false
    find-architects:
        output: true
resources_name: resources
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
favicon: /images/favicon-BOA.ico
google_analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
