title: 'Board of Architects'
title-abbreviated: BOA
description: 'The Board of Architects is the statutory authority established to administer the Architects Act in Singapore.'
url: 'https://www.boa.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
resources_name: resources
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/favicon-BOA.ico
google_analytics: null
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
colors:
  primary-color: '#2e509f'
  secondary-color: '#d9061c'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'
staging: https://isomer-boagovsg-staging.netlify.app
prod: https://isomer-boagovsg-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
